export const CURRENTHOUSES = [
  // when you get mutiple pics per house make the image value an array. sort houses into folders?
  {
    id: 0,
    name: "CurrentName0",
    images: [
        "https://picsum.photos/550",
        "https://picsum.photos/551",
        "https://picsum.photos/552",
        "https://picsum.photos/553",
        "https://picsum.photos/554",
        "https://picsum.photos/555",
        "https://picsum.photos/556",
        "https://picsum.photos/557",
        "https://picsum.photos/558",
        "https://picsum.photos/559",
        "https://picsum.photos/560",
    ],
    address: 1234,
    featured: false,
    description: "Description.",
    todo: "Add more info here",
  },
  {
    id: 1,
    name: "CurrentName1",
    images: [
        "https://picsum.photos/530",
        "https://picsum.photos/531",
        "https://picsum.photos/532",
        "https://picsum.photos/533",
        "https://picsum.photos/534",
        "https://picsum.photos/535",
        "https://picsum.photos/536",
        "https://picsum.photos/537",
        "https://picsum.photos/538",
        "https://picsum.photos/539",
        "https://picsum.photos/540",
    ],
    address: 1234,
    featured: false,
    description: "Description.",
    todo: "Add more info here",
  },
  {
    id: 2,
    name: "CurrentName2",
    images: [
        "https://picsum.photos/570",
        "https://picsum.photos/571",
        "https://picsum.photos/572",
        "https://picsum.photos/573",
        "https://picsum.photos/574",
        "https://picsum.photos/575",
        "https://picsum.photos/576",
        "https://picsum.photos/577",
        "https://picsum.photos/578",
        "https://picsum.photos/579",
        "https://picsum.photos/580",
    ],
    address: 1234,
    featured: false,
    description: "Description.",
    todo: "Add more info here",
  },
];
