export const HOUSES = [
         // when you get mutiple pics per house make the image value an array. sort houses into folders?
         {
           id: 0,
           name: "Name0",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 1,
           name: "Name1",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 2,
           name: "Name2",
           images: [
             "https://picsum.photos/502",
             "https://picsum.photos/510",
             "https://picsum.photos/511",
             "https://picsum.photos/512",
             "https://picsum.photos/513",
             "https://picsum.photos/514",
             "https://picsum.photos/515",
             "https://picsum.photos/516",
             "https://picsum.photos/517",
             "https://picsum.photos/518",
             "https://picsum.photos/519",
             "https://picsum.photos/520",
           ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 3,
           name: "Name3",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 4,
           name: "Name4",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 5,
           name: "Name5",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 6,
           name: "Name6",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 7,
           name: "Name7",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 8,
           name: "Name8",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
         {
           id: 9,
           name: "Name9",
           images: [
            "https://picsum.photos/502",
            "https://picsum.photos/510",
            "https://picsum.photos/511",
            "https://picsum.photos/512",
            "https://picsum.photos/513",
            "https://picsum.photos/514",
            "https://picsum.photos/515",
            "https://picsum.photos/516",
            "https://picsum.photos/517",
            "https://picsum.photos/518",
            "https://picsum.photos/519",
            "https://picsum.photos/520",
          ],
           address: 1234,
           featured: false,
           description: "Description.",
           todo: "Add more info here",
         },
       ];